### ISSUE TITLE
add drawings of neural net in notebook

### ISSUE THREAD

**Issue by rleriche** [rleriche/Optimization_AI_Cotonou_2022#16]
We may add some drawings in the notebook to illustrate the neural net structure, as was done in Question 1 about `sphereL1`. For example to illustrate 

```
inputs = np.array([[1,2,5,4],[1,0.2,0.15,0.024]])
weights = [
        np.array(
            [
                [1,0.2,0.5,1,-1],
                [2,1,3,5,0],
                [0.2,0.1,0.6,0.78,1]
            ]
        ),
    np.array(
            [
                [1,0.2,0.5,1],
                [2,1,3,5]
            ]
        )
    ]
activation = sigmoid
```

**Comment by BWhannou** [comment]
@rleriche @akouete-kpakpo 
is a graph like that what you had in mind? (I did it with latex :) )

![image](https://user-images.githubusercontent.com/9529168/184355340-e65eb4d6-86c2-4f84-9190-7af9ee98cf84.png)

**Comment by akouete-kpakpo** [comment]
@BWhannou yes! Thanks a lot.

Could you push the LaTeX code in a MR?

I believe there should be also a plot with how an artificial neuron process the information contained in entries (x_1, ..., x_4, 1) :
- weights matrix application to the entries and
- activation function application

**Comment by rleriche** [comment]
Nice, thanks!
