### ISSUE TITLE
There is a typo on slide 15 at position 1,1 in the Hessian matrix

### ISSUE THREAD

**Issue by akouete-kpakpo** [rleriche/Optimization_AI_Cotonou_2022#7]
@rleriche 

## Reference

![image](https://user-images.githubusercontent.com/26568112/181466292-74dc2106-6acf-4ab9-853a-a77c148e8fad.png)

https://github.com/rleriche/Optimization_AI_Cotonou_2022/blob/main/Slides_course/optim_ML_intro_course_EEIA2022.pdf

**Comment by rleriche** [comment]
Done, thx
