### ISSUE TITLE
Add a requirements.txt

### ISSUE THREAD

**Issue by akouete-kpakpo** [rleriche/Optimization_AI_Cotonou_2022#9]
## Context
Instructions to make function the code from 0. Here we suppose that students have jupyter, numpy etc. 

Obviously, it is not always the case and we had some bugs during training.

**Comment by BWhannou** [comment]
let's restructure the code as we are doing for the other repositories

**Comment by akouete-kpakpo** [comment]
@BWhannou ok

**Comment by BWhannou** [comment]
@akouete-kpakpo  I used the requirements for your decision tree course
https://github.com/rleriche/Optimization_AI_Cotonou_2022/blob/680bcfcf6f1ea40066c77d27715525f370c436d2/requirements/dev.txt

I will close this issue. You can reopen it, if you think necessary

**Comment by BWhannou** [comment]
@akouete-kpakpo  I used the requirements for your decision tree course
https://github.com/rleriche/Optimization_AI_Cotonou_2022/blob/680bcfcf6f1ea40066c77d27715525f370c436d2/requirements/dev.txt

I will close this issue. You can reopen it, if you think necessary
